#!/bin/bash
set -e
# 设置颜色变量
COLOR_DEFAULT="\e[0m"
COLOR_RED="\e[31m"
COLOR_GREEN="\e[32m"
COLOR_YELLOW="\e[33m"
COLOR_BLUE="\e[34m"
COLOR_PURPLE="\e[35m"
COLOR_CYAN="\e[36m"

interrupt_handler() {
    echo -e "${COLOR_YELLOW}[*] Received Ctrl+C, Do you want to continue running the script? (Y/n)${COLOR_DEFAULT}"
    read -r answer
    case $answer in
        [Nn]) exit 1;;
        *) continue;;
    esac
}
trap interrupt_handler SIGINT

if [ $# -lt 2 ]; then
    echo -e "${COLOR_YELLOW}[*] Please provide the target Github project address and target file name.${COLOR_DEFAULT}"
    exit 1
fi

MAIN_DIR="$HOME/JiuWei"
HBI_FILE=".have_been_install" #记录所有已安装的包名（文本文件）
PACKAGES_INFO=".packages_info" #记录所有的包信息,方便search（文本文件）
PACKAGES_NAME=".packages_name" #记录所有的包名称,方便install（文本文件）
CONFIG_FILE="config.list" #配置文件（文本文件）
FOXINDEX_FILE=".foxindex" #放置FOXINDEX解压后产生的文件（文件夹）
CACHE_FILE=".cache" #放置从源中下载的安装包（文件夹）
BIN_FILE=".bin" #快捷命令存放（文件夹）
ST_FILE=".status" #JiuWei状态检测（文本文件）
DEFAULT_ANSWER=Y

HBI="$MAIN_DIR/$HBI_FILE"
PACKAGES_INFO="$MAIN_DIR/$PACKAGES_INFO"
PACKAGES_NAME="$MAIN_DIR/$PACKAGES_NAME"
CACHE="$MAIN_DIR/$CACHE_FILE"
FOXINDEX="$MAIN_DIR/$FOXINDEX_FILE"
BIN="$MAIN_DIR/$BIN_FILE"
ST="$MAIN_DIR/$ST_FILE"

#get_latest_releases "chaitin/xray" "arm64" "xray" "xray"

github_repo=$1
arch=$2
keyword=$3
output_filename=$4

latest_release=$(curl -sL "https://api.github.com/repos/$repo/releases/latest")
download_urls=$(echo "$latest_release" | grep -oE '"browser_download_url": "[^"]+"' | cut -d'"' -f4)
for url in $download_urls; do
    if [[ $url == *"$arch"* ]]; then
        target_file=${url##*/}
        wget "$url" -O "$CACHE/$target_file"
    fi
done
cd $CACHE
if [[ $target_file == *.tar.gz ]]; then
    tar -zxvf "$target_file" --to-command="grep -q '$keyword' && cat > $BIN/$output_filename"
elif [[ $target_file == *.zip ]]; then
    unzip -p "$target_file" | grep -q "$keyword" > "$BIN/$output_filename"
else
    echo "[-] 不支持的文件格式"
fi